# Step = 1 :  Data collection

In [1]:
! pip install ucimlrepo 
from ucimlrepo import fetch_ucirepo 
! pip install pandas
import pandas as pd
  
# fetch dataset 
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17) 
  
#  get features andtargets
X = breast_cancer_wisconsin_diagnostic.data.features 
y = breast_cancer_wisconsin_diagnostic.data.targets 
# combine features and targets into a single dataframe
df =pd.concat([X,y], axis=1)
# convert to csv file
df.to_csv("breast_cancer_wisconsin_diagnostic.csv", index=False)
print("Dataset saved as breast_cancer_wisconsin_diagnostic.csv")

Requirement already satisfied: ucimlrepo in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from ucimlrepo) (3.0.6)
Requirement already satisfied: certifi>=2020.12.5 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from ucimlrepo) (2026.10.18)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Requirement already satisfied: pandas in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Dataset saved as breast_cancer_wisconsin_diagnostic.csv

# Step =2 : Import Labraries

In [2]:
! pip install pandas
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
! pip install numpy
import numpy as  np
! pip install plotly
import plotly.express as px
import plotly.graph_objects as go 
! pip install scikit-learn
import sklearn as sk
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print("All libraries are imported successfully!")

Requirement already satisfied: pandas in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (2.4.6)
Requirement already satisfied: plotly in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (7.1.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from plotly) (2.27.1)
Requirement already satisfied: packaging in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from plotly) (26.3)
Requirement already satisfied: scikit-learn in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
All libraries are imported successfully!

# Step = 3 : Data Load and Display First Five Rows

In [3]:
df =pd.read_csv("breast_cancer_wisconsin_diagnostic.csv")
# Display first five rows
print("Display first five rows")
df.head()

Display first five rows

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

# Step = 4 : UnderStanding the Datasets

In [4]:
# check the information of the dataset
print("check the information of the dataset:")
print(df.info())
# check the datatypes of the dataset
print("check the datatype:")
print(df.dtypes)
# Descrine of the dataset
print("describe of the dataset:")
print(df.describe())
# check the shape of the dataset
print("shape of the dataset:")
print(df.shape)

check the information of the dataset:
<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   radius1             569 non-null    float64
 1   texture1            569 non-null    float64
 2   perimeter1          569 non-null    float64
 3   area1               569 non-null    float64
 4   smoothness1         569 non-null    float64
 5   compactness1        569 non-null    float64
 6   concavity1          569 non-null    float64
 7   concave_points1     569 non-null    float64
 8   symmetry1           569 non-null    float64
 9   fractal_dimension1  569 non-null    float64
 10  radius2             569 non-null    float64
 11  texture2            569 non-null    float64
 12  perimeter2          569 non-null    float64
 13  area2               569 non-null    float64
 14  smoothness2         569 non-null    float64
 15  compactness2        569 non-null    float64
 16  concavity2          569 non-null    float64
 17  concave_points2     569 non-null    float64
 18  symmetry2           569 non-null    float64
 19  fractal_dimension2  569 non-null    float64
 20  radius3             569 non-null    float64
 21  texture3            569 non-null    float64
 22  perimeter3          569 non-null    float64
 23  area3               569 non-null    float64
 24  smoothness3         569 non-null    float64
 25  compactness3        569 non-null    float64
 26  concavity3          569 non-null    float64
 27  concave_points3     569 non-null    float64
 28  symmetry3           569 non-null    float64
 29  fractal_dimension3  569 non-null    float64
 30  Diagnosis           569 non-null    str
dtypes: float64(30), str(1)
memory usage: 137.9 KB
None
check the datatype:
radius1               float64
texture1              float64
perimeter1            float64
area1                 float64
smoothness1           float64
compactness1          float64
concavity1            float64
concave_points1       float64
symmetry1             float64
fractal_dimension1    float64
radius2               float64
texture2              float64
perimeter2            float64
area2                 float64
smoothness2           float64
compactness2          float64
concavity2            float64
concave_points2       float64
symmetry2             float64
fractal_dimension2    float64
radius3               float64
texture3              float64
perimeter3            float64
area3                 float64
smoothness3           float64
compactness3          float64
concavity3            float64
concave_points3       float64
symmetry3             float64
fractal_dimension3    float64
Diagnosis                 str
dtype: object
describe of the dataset:
          radius1    texture1  perimeter1        area1  smoothness1  \
count  569.000000  569.000000  569.000000   569.000000   569.000000
mean    14.127292   19.289649   91.969033   654.889104     0.096360
std      3.524049    4.301036   24.298981   351.914129     0.014064
min      6.981000    9.710000   43.790000   143.500000     0.052630
25%     11.700000   16.170000   75.170000   420.300000     0.086370
50%     13.370000   18.840000   86.240000   551.100000     0.095870
75%     15.780000   21.800000  104.100000   782.700000     0.105300
max     28.110000   39.280000  188.500000  2501.000000     0.163400

       compactness1  concavity1  concave_points1   symmetry1  \
count    569.000000  569.000000       569.000000  569.000000
mean       0.104341    0.088799         0.048919    0.181162
std        0.052813    0.079720         0.038803    0.027414
min        0.019380    0.000000         0.000000    0.106000
25%        0.064920    0.029560         0.020310    0.161900
50%        0.092630    0.061540         0.033500    0.179200
75%        0.130400    0.130700         0.074000    0.195700
max        0.345400    0.426800         0.201200    0.304000

       fractal_dimension1  ...     radius3    texture3  perimeter3  \
count          569.000000  ...  569.000000  569.000000  569.000000
mean             0.062798  ...   16.269190   25.677223  107.261213
std              0.007060  ...    4.833242    6.146258   33.602542
min              0.049960  ...    7.930000   12.020000   50.410000
25%              0.057700  ...   13.010000   21.080000   84.110000
50%              0.061540  ...   14.970000   25.410000   97.660000
75%              0.066120  ...   18.790000   29.720000  125.400000
max              0.097440  ...   36.040000   49.540000  251.200000

             area3  smoothness3  compactness3  concavity3  concave_points3  \
count   569.000000   569.000000    569.000000  569.000000       569.000000
mean    880.583128     0.132369      0.254265    0.272188         0.114606
std     569.356993     0.022832      0.157336    0.208624         0.065732
min     185.200000     0.071170      0.027290    0.000000         0.000000
25%     515.300000     0.116600      0.147200    0.114500         0.064930
50%     686.500000     0.131300      0.211900    0.226700         0.099930
75%    1084.000000     0.146000      0.339100    0.382900         0.161400
max    4254.000000     0.222600      1.058000    1.252000         0.291000

        symmetry3  fractal_dimension3
count  569.000000          569.000000
mean     0.290076            0.083946
std      0.061867            0.018061
min      0.156500            0.055040
25%      0.250400            0.071460
50%      0.282200            0.080040
75%      0.317900            0.092080
max      0.663800            0.207500

[8 rows x 30 columns]
shape of the dataset:
(569, 31)

In [5]:
# check the null values in a dataset
print("check the null values:")
print(df.isnull().sum())
# check the dublicate values in a dataset
print("display dublicate values:")
print(df.duplicated().sum())

check the null values:
radius1               0
texture1              0
perimeter1            0
area1                 0
smoothness1           0
compactness1          0
concavity1            0
concave_points1       0
symmetry1             0
fractal_dimension1    0
radius2               0
texture2              0
perimeter2            0
area2                 0
smoothness2           0
compactness2          0
concavity2            0
concave_points2       0
symmetry2             0
fractal_dimension2    0
radius3               0
texture3              0
perimeter3            0
area3                 0
smoothness3           0
compactness3          0
concavity3            0
concave_points3       0
symmetry3             0
fractal_dimension3    0
Diagnosis             0
dtype: int64
display dublicate values:
0

# Step = 5 :  EDA

In [6]:
fig = px.histogram(
    df,
    x="Diagnosis",
    color="Diagnosis",
    title="Distribution of Breast Cancer Diagnosis",
    text_auto=True,
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Diagnosis",
    yaxis_title="Count"
)

fig.show()

In [7]:
diagnosis_counts = df["Diagnosis"].value_counts().reset_index()
diagnosis_counts.columns = ["Diagnosis", "Count"]

fig = px.pie(
    diagnosis_counts,
    names="Diagnosis",
    values="Count",
    title="Benign vs Malignant Cases",
    hole=0.4,
    color="Diagnosis",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_traces(
    textinfo="label+percent+value",
    pull=[0.05, 0]
)

fig.update_layout(template="plotly_white")
fig.show()

In [8]:
missing = df.isnull().sum().reset_index()
missing.columns = ["Feature", "Missing Values"]

missing = missing[missing["Missing Values"] > 0]

if missing.empty:
    print("No missing values found.")
else:
    fig = px.bar(
        missing,
        x="Feature",
        y="Missing Values",
        title="Missing Values by Feature",
        text_auto=True
    )
    fig.update_layout(template="plotly_white")
    fig.show()

No missing values found.

In [9]:
numeric_df = df.select_dtypes(include="number")
corr = numeric_df.corr()

fig = px.imshow(
    corr,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
    title="Feature Correlation Heatmap"
)

fig.update_layout(
    template="plotly_white",
    height=900,
    width=1000
)

fig.show()

In [10]:
features = [
    "radius1",
    "texture1",
    "perimeter1",
    "area1",
    "smoothness1",
    "compactness1",
    "concavity1",
    "concave_points1",
    "symmetry1",
    "fractal_dimension1"
]

for feature in features:
    fig = px.histogram(
        df,
        x=feature,
        color="Diagnosis",
        marginal="box",
        barmode="overlay",
        opacity=0.7,
        title=f"Distribution of {feature} by Diagnosis",
        color_discrete_sequence=px.colors.qualitative.Set1
    )

    fig.update_layout(template="plotly_white")
    fig.show()

In [11]:
for feature in features:
    fig = px.box(
        df,
        x="Diagnosis",
        y=feature,
        color="Diagnosis",
        points="outliers",
        title=f"Outlier Analysis: {feature}",
        color_discrete_sequence=px.colors.qualitative.Set2
    )

    fig.update_layout(template="plotly_white")
    fig.show()

In [12]:
fig = px.scatter(
    df,
    x="radius1",
    y="perimeter1",
    color="Diagnosis",
    size="area1",
    hover_data=["texture1", "smoothness1"],
    title="Radius vs Perimeter by Diagnosis",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(template="plotly_white")
fig.show()

In [13]:
target = df["Diagnosis"].map({"M": 1, "B": 0})

correlations = (
    numeric_df.corrwith(target)
    .dropna()
    .sort_values(key=abs, ascending=False)
)

correlation_df = correlations.reset_index()
correlation_df.columns = ["Feature", "Correlation"]

fig = px.bar(
    correlation_df.head(15),
    x="Correlation",
    y="Feature",
    orientation="h",
    color="Correlation",
    color_continuous_scale="RdBu_r",
    range_color=[-1, 1],
    title="Top 15 Features Correlated with Diagnosis"
)

fig.update_layout(
    template="plotly_white",
    yaxis={"categoryorder": "total ascending"}
)

fig.show()

# Step = 6 : Data preprocessing

In [14]:
le = LabelEncoder()
df["Diagnosis"] =le.fit_transform(df["Diagnosis"])
df.head()

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,1
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,1
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,1
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,1
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,1

In [15]:
# separate features and target variable
X = df.drop("Diagnosis", axis=1)
y = df["Diagnosis"]
print(X.shape)
print(y.shape)

(569, 30)
(569,)

In [16]:
# separate training and testing data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

     radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
68     9.029     17.33       58.79   250.5      0.10660       0.14130
181   21.090     26.57      142.70  1311.0      0.11410       0.28320
63     9.173     13.86       59.20   260.9      0.07721       0.08751
248   10.650     25.22       68.01   347.0      0.09657       0.07234
60    10.170     14.88       64.55   311.9      0.11340       0.08061
..       ...       ...         ...     ...          ...           ...
71     8.888     14.64       58.79   244.0      0.09783       0.15310
106   11.640     18.33       75.17   412.5      0.11420       0.10170
270   14.290     16.82       90.30   632.6      0.06429       0.02675
435   13.980     19.62       91.12   599.5      0.10600       0.11330
102   12.180     20.52       77.22   458.7      0.08013       0.04038

     concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
68      0.31300          0.04375     0.2111             0.08046  ...   10.310
181     0.24870          0.14960     0.2395             0.07398  ...   26.680
63      0.05988          0.02180     0.2341             0.06963  ...   10.010
248     0.02379          0.01615     0.1897             0.06329  ...   12.250
60      0.01084          0.01290     0.2743             0.06960  ...   11.020
..          ...              ...        ...                 ...  ...      ...
71      0.08606          0.02872     0.1902             0.08980  ...    9.733
106     0.07070          0.03485     0.1801             0.06520  ...   13.140
270     0.00725          0.00625     0.1508             0.05376  ...   14.910
435     0.11260          0.06463     0.1669             0.06544  ...   17.040
102     0.02383          0.01770     0.1739             0.05677  ...   13.340

     texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
68      22.65       65.50   324.7      0.14820       0.43650     1.25200
181     33.48      176.50  2089.0      0.14910       0.75840     0.67800
63      19.23       65.59   310.1      0.09836       0.16780     0.13970
248     35.19       77.98   455.7      0.14990       0.13980     0.11250
60      17.45       69.86   368.6      0.12750       0.09866     0.02168
..        ...         ...     ...          ...           ...         ...
71      15.67       62.56   284.4      0.12070       0.24360     0.14340
106     29.26       85.51   521.7      0.16880       0.26600     0.28730
270     20.65       94.44   684.6      0.08567       0.05036     0.03866
435     30.80      113.90   869.3      0.16130       0.35680     0.40690
102     32.84       84.58   547.8      0.11230       0.08862     0.11450

     concave_points3  symmetry3  fractal_dimension3
68           0.17500     0.4228             0.11750
181          0.29030     0.4098             0.12840
63           0.05087     0.3282             0.08490
248          0.06136     0.3409             0.08147
60           0.02579     0.3557             0.08020
..               ...        ...                 ...
71           0.04786     0.2254             0.10840
106          0.12180     0.2806             0.09097
270          0.03333     0.2458             0.06120
435          0.18270     0.3179             0.10550
102          0.07431     0.2694             0.06878

[455 rows x 30 columns]
     radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
204    12.47     18.60       81.09   481.9      0.09965       0.10580
70     18.94     21.31      123.60  1130.0      0.09009       0.10290
131    15.46     19.48      101.70   748.9      0.10920       0.12230
431    12.40     17.68       81.47   467.8      0.10540       0.13160
540    11.54     14.44       74.65   402.9      0.09984       0.11200
..       ...       ...         ...     ...          ...           ...
486    14.64     16.85       94.21   666.0      0.08641       0.06698
75     16.07     19.65      104.10   817.7      0.09168       0.08424
249    11.52     14.93       73.87   406.3      0.10130       0.07808
238    14.22     27.85       92.55   623.9      0.08223       0.10390
265    20.73     31.12      135.70  1419.0      0.09469       0.11430

     concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
204     0.08005          0.03821     0.1925             0.06373  ...    14.97
70      0.10800          0.07951     0.1582             0.05461  ...    24.86
131     0.14660          0.08087     0.1931             0.05796  ...    19.26
431     0.07741          0.02799     0.1811             0.07102  ...    12.88
540     0.06737          0.02594     0.1818             0.06782  ...    12.26
..          ...              ...        ...                 ...  ...      ...
486     0.05192          0.02791     0.1409             0.05355  ...    16.46
75      0.09769          0.06638     0.1798             0.05391  ...    19.77
249     0.04328          0.02929     0.1883             0.06168  ...    12.65
238     0.11030          0.04408     0.1342             0.06129  ...    15.75
265     0.13670          0.08646     0.1769             0.05674  ...    32.49

     texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
204     24.64       96.05   677.9       0.1426        0.2378      0.2671
70      26.58      165.90  1866.0       0.1193        0.2336      0.2687
131     26.00      124.90  1156.0       0.1546        0.2394      0.3791
431     22.91       89.61   515.8       0.1450        0.2629      0.2403
540     19.68       78.78   457.8       0.1345        0.2118      0.1797
..        ...         ...     ...          ...           ...         ...
486     25.44      106.00   831.0       0.1142        0.2070      0.2437
75      24.56      128.80  1223.0       0.1500        0.2045      0.2829
249     21.19       80.88   491.8       0.1389        0.1582      0.1804
238     40.54      102.50   764.0       0.1081        0.2426      0.3064
265     47.16      214.00  3432.0       0.1401        0.2644      0.3442

     concave_points3  symmetry3  fractal_dimension3
204          0.10150     0.3014             0.08750
70           0.17890     0.2551             0.06589
131          0.15140     0.2837             0.08019
431          0.07370     0.2556             0.09359
540          0.06918     0.2329             0.08134
..               ...        ...                 ...
486          0.07828     0.2455             0.06596
75           0.15200     0.2650             0.06387
249          0.09608     0.2664             0.07809
238          0.08219     0.1890             0.07796
265          0.16590     0.2868             0.08218

[114 rows x 30 columns]
68     0
181    1
63     0
248    0
60     0
      ..
71     0
106    0
270    0
435    1
102    0
Name: Diagnosis, Length: 455, dtype: int64
204    0
70     1
131    1
431    0
540    0
      ..
486    0
75     1
249    0
238    0
265    1
Name: Diagnosis, Length: 114, dtype: int64

In [17]:
# apply standardscaler to the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step = 7 : Building Model

In [18]:
%pip install xgboost

Requirement already satisfied: xgboost in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

In [19]:

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Define models
Models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SVM": SVC(probability=True, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    )
}

# Step =8 :  Train and evaluation

In [20]:
%pip install scikit-learn

import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix as cm
)

for name, model in Models.items():

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    print("\n" + "=" * 50)
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")

    print("\nClassification Report:")
    print(classification_report(
        y_test,
        y_pred,
        labels=[0, 1],
        target_names=["Benign", "Malignant"],
        zero_division=0
    ))

    print("Confusion Matrix:")
    print(cm(y_test, y_pred, labels=[0, 1]))

Requirement already satisfied: scikit-learn in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\DELL\miniconda3\envs\Breast_Cancer_prediction\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

==================================================
Model: Logistic Regression
Accuracy: 97.37%

Classification Report:
              precision    recall  f1-score   support

      Benign       0.97      0.99      0.98        71
   Malignant       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Confusion Matrix:
[[70  1]
 [ 2 41]]

==================================================
Model: SVM
Accuracy: 98.25%

Classification Report:
              precision    recall  f1-score   support

      Benign       0.97      1.00      0.99        71
   Malignant       1.00      0.95      0.98        43

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

Confusion Matrix:
[[71  0]
 [ 2 41]]

==================================================
Model: Random Forest
Accuracy: 96.49%

Classification Report:
              precision    recall  f1-score   support

      Benign       0.96      0.99      0.97        71
   Malignant       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Confusion Matrix:
[[70  1]
 [ 3 40]]

==================================================
Model: XGBoost
Accuracy: 95.61%

Classification Report:
              precision    recall  f1-score   support

      Benign       0.96      0.97      0.97        71
   Malignant       0.95      0.93      0.94        43

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Confusion Matrix:
[[69  2]
 [ 3 40]]

In [35]:
import joblib

# Save the trained SVM model
joblib.dump(
    Models["SVM"],
    "breast_cancer_model.joblib"
)

print("SVM model saved successfully!")

SVM model saved successfully!

In [37]:
import joblib
import os

# Save the already-fitted scaler
joblib.dump(scaler, "scaler.joblib")

print("Scaler saved:", os.path.exists("scaler.joblib"))
print("Saved location:", os.path.abspath("scaler.joblib"))

Scaler saved: True
Saved location: c:\Users\DELL\Downloads\Breast_Cancer_Prediction_ML_Project\scaler.joblib